# .github/workflows/seed-pexels.yml
name: Seed Pexels Assets

# All triggers are commented out to disable automatic and manual runs
# on:
#   schedule:
#     - cron: '0 3 * * *'  # DISABLED: runs daily at 3 AM UTC
#   workflow_dispatch:     # DISABLED: manual run from UI

jobs:
  seed-assets:
    if: false  # ensures job never runs even if triggered
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies (with dev-deps)
        run: npm ci --include=dev

      - name: Install FFmpeg
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg

      - name: Seed Pexels Assets
        env:
          SUPABASE_URL:              ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
          PEXELS_API_KEY:            ${{ secrets.PEXELS_API_KEY }}
        run: npm run seed:pexels
